export const countryActionTypes = {
  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAIL: "GET_COUNTRIES_FAIL",
};

export const continentActionTypes = {
  GET_CONTINENTS_REQUEST: "GET_CONTINENTS_REQUEST",
  GET_CONTINENTS_SUCCESS: "GET_CONTINENTS_SUCCESS",
  GET_CONTINENTS_FAIL: "GET_CONTINENTS_FAIL",
};
